### ISSUE TITLE
place names contain many duplicates

### ISSUE THREAD

**Issue by JonathanReeve** [JonathanReeve/sanger#43]
See for example: 
 * Washington, D.C. (eight duplicates) 
 * New York City (around six duplicates)

**Comment by CathyHajo** [comment]
We are working on cleaning that up manually, during our proofread, but once we get the site search working can use that to locate and correct any that remain.

**Comment by CathyHajo** [comment]
Have cleaned it all up, save for some outliers that won't come out of the drop down even though I removed them from documents.
