### ISSUE TITLE
Journal titles containing double quotes break hyperlinks

### ISSUE THREAD

**Issue by JonathanReeve** [JonathanReeve/sanger#54]
This is really only a problem with the journal called `Community Church of Boston, "Birth Control and Civil Liberties"` which seems not to be the name of a journal, but rather some other context. Was this a pamphlet? 

Possible solution: rename journal title above `Community Church of Boston`, or `Community Church of Boston pamphlet`.

**Comment by CathyHajo** [comment]
This is a book. I can change the name to Birth Control and Civil Liberties, the Church was the author. I just corrected it in our newest version.
