### ISSUE TITLE
copy over static landing page

### ISSUE THREAD

**Issue by JonathanReeve** [JonathanReeve/sanger#80]
From http://www.nyu.edu/projects/sanger/webedition/app/

**Comment by EstherKatz** [comment]
Jonathan,

Thanks!

On Thu, Apr 2, 2015 at 9:10 AM, Jonathan Reeve <notifications@github.com>
wrote:

> From http://www.nyu.edu/projects/sanger/webedition/app/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JonathanReeve/sanger/issues/80>.
>



-- 
Dr. Esther Katz
Editor/Director
Margaret Sanger Papers Project
New York University
838 Broadway, Suite 504
New York, NY 10003-4812

TEL. 212 998-8620
Fax: 212-995-3968
E-mail: esther.katz@nyu.edu

Visit our web site at: http://www.nyu.edu/projects/sanger

**Comment by JonathanReeve** [comment]
The right way to do this is probably to do #66 first, and have a nice URL structure for the whole site. In the meantime, though, just to put something decent up, I copied over `index.html` from the original site, and placed it in `app/`. (This is in 527dcd40e.) To keep it under VC, but have it be available at the root, I have an ugly hack in the form of a symlink that symlinks it from `app/` back to root, which explains why the paths are all relative to `../..` instead of `app/`. In other words: warning! Temporary fix. 

The landing page at http://sangerpapers.org should be good now, at least temporarily.
